package com.item_management.service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import com.item_management.data.BlockedItemsSavedData.BlockedEntryData;

import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.storage.LevelResource;

public final class DefaultRuleExportService {
    private static final String EXPORT_FILE_NAME = "itemmanagement-exported-default-world-rules.toml";

    private DefaultRuleExportService() {}

    public static Path exportWorldRules(MinecraftServer server, List<BlockedEntryData> entries) throws IOException {
        Path exportPath = server.getWorldPath(LevelResource.ROOT).resolve(EXPORT_FILE_NAME);
        Files.writeString(exportPath, buildToml(entries), StandardCharsets.UTF_8);
        return exportPath;
    }

    private static String buildToml(List<BlockedEntryData> entries) {
        List<String> flattenedRules = new ArrayList<>();
        for (BlockedEntryData entry : entries) {
            for (var itemId : entry.itemIds()) {
                flattenedRules.add("\"" + itemId + "=" + entry.replacementId() + "\"");
            }
        }

        StringBuilder builder = new StringBuilder();
        builder.append("# Generated by itemmanagement on ")
                .append(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME))
                .append('\n');
        builder.append("# Copy these values into your pack config if you want to reuse this world's rules as defaults.\n");
        builder.append("defaultWorldRulesEnabled = true\n");
        builder.append("defaultWorldItemReplacements = [\n");
        for (int index = 0; index < flattenedRules.size(); index++) {
            builder.append("  ").append(flattenedRules.get(index));
            if (index < flattenedRules.size() - 1) {
                builder.append(',');
            }
            builder.append('\n');
        }
        builder.append("]\n");
        return builder.toString();
    }
}
